# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2
project_name: monteverdi

before:
  hooks:
    - go mod tidy

builds:
  - id: monteverdi
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
      - -X github.com/maroda/monteverdi/display.Version={{.Version}}

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    extra_files:
      - config.json
    image_templates:
      - "ghcr.io/maroda/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/maroda/{{ .ProjectName }}:latest-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    extra_files:
      - config.json
    image_templates:
      - "ghcr.io/maroda/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "ghcr.io/maroda/{{ .ProjectName }}:latest-arm64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

docker_manifests:
  - name_template: "ghcr.io/maroda/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/maroda/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/maroda/{{ .ProjectName }}:{{ .Version }}-arm64"
  - name_template: "ghcr.io/maroda/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/maroda/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/maroda/{{ .ProjectName }}:latest-arm64"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
