# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/maroda/monteverdi/display.Version={{.Version}}
    # Exclude invalid combinations
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - web/**/*
      - config.json
      - README.md
      - LICENSE

# Docker images for GitHub Container Registry
dockers:
  - image_templates:
      - "ghcr.io/maroda/monteverdi:{{ .Version }}-amd64"
      - "ghcr.io/maroda/monteverdi:latest-amd64"
    use: buildx
    dockerfile: Dockerfile
    extra_files:
      - go.mod
      - config.json
      - web/
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/maroda/monteverdi"

  - image_templates:
      - "ghcr.io/maroda/monteverdi:{{ .Version }}-arm64"
      - "ghcr.io/maroda/monteverdi:latest-arm64"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    extra_files:
      - go.mod
      - config.json
      - web/
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/maroda/monteverdi"

# Multi-arch manifest
docker_manifests:
  - name_template: "ghcr.io/maroda/monteverdi:{{ .Version }}"
    image_templates:
      - "ghcr.io/maroda/monteverdi:{{ .Version }}-amd64"
      - "ghcr.io/maroda/monteverdi:{{ .Version }}-arm64"

  - name_template: "ghcr.io/maroda/monteverdi:latest"
    image_templates:
      - "ghcr.io/maroda/monteverdi:latest-amd64"
      - "ghcr.io/maroda/monteverdi:latest-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: maroda
    name: monteverdi
  footer: >-
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).